version: "3.8"

services:
  api:
    volumes:
      - ./src:/app/src
      - ./llm_sentiment:/app/llm_sentiment
      - ./consumers:/app/consumers
    command: uvicorn python -m src.main:app --host 0.0.0.0 --port 80 --reload

